version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nihei9/meaningless-cli
    steps:
      - checkout
      - run: |
        go get -v -t -d ./...
        go test -v ./...
        go build -o meaningless ./main.go
        ./meaningless --version
